############ Application name ##############

spring:
  application:
    name: fuxpin-role-microservice


####### POSTGRESQL Configuration #########
  jpa:
    hibernate:
      ## To avoid conflicts, the automatic schema creation is turned off / update -> To create database if is not created
      # -> ddl-auto: update
      ddl-auto: none
    # show-sql: true -> Show SQL
  datasource:
    ## Database is not embedded. Spring Boot 2 - external database
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://pi.intranet.cat:5432/aplicaciondeventas-legacy
    username: ${postgresql.user}
    password: ${postgresql.password}

############ Application port ##############
server:
  # Spring Boot choose a random port for us because later we are accessing this service with its name.
  port: 0

############ EUREKA SERVER configuration ##############
eureka:
  client:
    serviceUrl:
      # defaultZone: ${EUREKA_URI:https://xrodrig.dnsnet.info:8446/eureka/}
      defaultZone: ${EUREKA_URI:https://pi.intranet.cat:8448/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

logging:
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:
    name: C:\Users\amgri\logs\fuxpin-config-server\fuxpin-legacy-role-microservice.log
  logback:
    rollingpolicy:
      clean-history-on-start: true

