spring:
  application:
    name: fuxpin-role-microservice

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://xrodrig.dnsnet.info:8446/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

