-- After data-postgresql is executed, data-postgre.sql is executed

INSERT INTO REGISTERED_USER ( USER_NAME, NAME, SURNAME1, SURNAME2) VALUES('xrodrig', 'Xavier', 'Rodríguez', 'Angrill');

INSERT INTO ROLES( CODE, DESCRIPTION, ID_USER ) VALUES('ROLE_ADMIN', 'ADMINISTRATION', 1);
INSERT INTO ROLES( CODE, DESCRIPTION, ID_USER ) VALUES('ROLE_MANAGER', 'Gestor', 1);
INSERT INTO ROLES( CODE, DESCRIPTION, ID_USER ) VALUES('ROLE_USER', 'Usuario', 1);

